---
- hosts: repo1
  become: true
  tasks:
    - name: Papulate Service Facts
      service_facts:
    - name: See the Service <httpd> facts as they are"
      debug:
        msg: "{{ ansible_facts.services['httpd.service'].state }}"
      register: http_service_status
    - name: Debug output
      debug:
        var: http_service_status
    - name: Check website path details
      shell: httpd -S | grep -e "port 443" | awk '{print $NF}' | awk -F ":" '{print $1}' | tr "(" " " |  awk '{ gsub(/ /,""); print }'
      register: path_output
      when: http_service_status.msg == "running"
    - name: Print path details
      debug:
        var: path_output.stdout_lines
    - name: Fetch SSL certificate path details
      shell: |
        grep -i -r SSLCertificateFile "{{ item }}" | awk '{print $NF}'
      with_items: "{{ path_output.stdout_lines }}"
      ignore_errors: true
      register: cert_path
    - name: Print path details
      debug:
        var: cert_path
    - name: Find subject of SSL
      shell: openssl x509 -noout -subject -in "{{ item.stdout }}"
      with_items: "{{ cert_path.results }}"
      loop_control:
        label: "{{ item.stdout }}"
      register: cert_subject
      ignore_errors: true
    - name: Dump <cert_subject>
      debug:
        var: cert_subject
    - name: Find exact certificate that need to replace
      set_fact:
        certificate_path: "{{ certificate_path|default([]) + [({'src_path': item.item.stdout, 'subject_detail': item.stdout})] }}"
      with_items: "{{ cert_subject.results | json_query('[*]')}}"
    - name: Dump << certificate_path >> details
      debug: var=certificate_path
    - name: Copy <<.CRT>> Certificate file on Server
      copy:
        src: /home/admin/certificate.crt
        dest: "{{ item.src_path }}"
        backup: true
        owner: root
        group: root
        mode: 0600
      with_items: "{{ certificate_path }}"
      ignore_errors: true
      when: item.subject_detail.find('ibexglobal.com') != -1 and item.src_path.find('.crt') != -1
    - name: Copy <<.PEM>> Certificate file on Server
      copy:
        src: /home/admin/certificate.crt
        dest: "{{ item.src_path }}"
        backup: true
      with_items: "{{ certificate_path }}"
      ignore_errors: true
      when: item.subject_detail.find('ibexglobal.com') != -1 and item.src_path.find('.pem') != -1
